.\"
.\" gnome-about manual page.
.\" (C) 2010 Vincent Untz (vuntz@gnome.org)
.\"
.TH GNOME-ABOUT 1 "GNOME"
.SH NAME
gnome-about \- Learn more about GNOME
.SH SYNOPSIS
.B gnome-about [\-\-gnome-version]
.SH DESCRIPTION
The \fIgnome-about\fP program is a tool to learn more about GNOME and
who creates GNOME. It contains an introduction about the project, and
lists all contributors.
.PP
The list of contributors used by \fIgnome-about\fP is the list of
GNOME Foundation members.
.SH OPTIONS
The following options are supported:
.TP
.I "--gnome-version"
Output the GNOME version instead of running a graphical interface.
.SH BUGS
If you find bugs in the \fIgnome-about\fP program, please report
these on http://bugzilla.gnome.org.
