# Generated automatically from Makefile.in by configure.
# Makefile.in generated automatically by automake 1.3 from Makefile.am

# Copyright (C) 1994, 1995, 1996, 1997, 1998 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# automake does not yet dig .sgml files, so for now the DocBook files
# must be extra_dist.  Also, in the future we should distribute the
# HTML files so that people without DocBook can still use the docs.

# This is ugly and quickly copied from the gtt approach


SHELL = /bin/sh

srcdir = .
top_srcdir = ..
prefix = /opt/gnome
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DISTDIR =

pkgdatadir = $(datadir)/gnome-core
pkglibdir = $(libdir)/gnome-core
pkgincludedir = $(includedir)/gnome-core

top_builddir = ..

ACLOCAL = aclocal -I macros
AUTOCONF = autoconf
AUTOMAKE = automake
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL_PROGRAM}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = i586-pc-linux-gnu
host_triplet = i586-pc-linux-gnu
CATALOGS =  it.gmo ko.gmo fr.gmo de.gmo es.gmo no.gmo
CATOBJEXT = .gmo
CC = gcc
CDROM_HOST = linux
CFLAGS = -g -O2
CPPFLAGS =  -I/opt/gnome/lib/glib/include -I/opt/gnome/include -I/usr/X11R6/include
CXX = c++
DATADIRNAME = share
DL_LIB = -ldl
GENCAT = 
GMOFILES =  it.gmo ko.gmo fr.gmo de.gmo es.gmo no.gmo
GMSGFMT = /usr/bin/msgfmt
GNOMEUI_LIBS = -lgnomeui -lgnome -lgnomesupport -ldl -lgdk_imlib -ltiff -lgif -ljpeg -lpng -lz -lSM -lICE -L/opt/gnome/lib -L/usr/X11R6/lib -lgtk -lgdk -lglib -lXext -lX11 -lm
GNOME_INCLUDEDIR = -I/opt/gnome/include -DNEED_GNOMESUPPORT_H -I/opt/gnome/lib/gnome-libs/include -I/opt/gnome/lib/glib/include -I/opt/gnome/include -I/usr/X11R6/include
GNOME_LIBDIR = -L/opt/gnome/lib
GNOME_LIBS = -lgnome -lgnomesupport -ldl
GTKXMHTML_LIBS = -lgtkxmhtml -lXpm -ljpeg -lpng -lz -lSM -lICE -L/opt/gnome/lib -L/usr/X11R6/lib -lgtk -lgdk -lglib -lXext -lX11 -lm
GTK_CFLAGS = -I/opt/gnome/lib/glib/include -I/opt/gnome/include -I/usr/X11R6/include
GTK_CONFIG = /opt/gnome/bin/gtk-config
GTK_LIBS = -lSM -lICE -L/opt/gnome/lib -L/usr/X11R6/lib -lgtk -lgdk -lglib -lXext -lX11 -lm
GT_NO = 
GT_YES = #YES#
INCLUDE_LOCALE_H = #include <locale.h>
INSTOBJEXT = .mo
INTLDEPS = 
INTLLIBS = 
INTLOBJS = 
LD = /usr/bin/ld
LDFLAGS = 
LEX = flex
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LN_S = ln -s
MAINT = 
MAKEINFO = makeinfo
MKINSTALLDIRS = ./mkinstalldirs
MSGFMT = /usr/bin/msgfmt
NM = /usr/bin/nm -B
PACKAGE = gnome-core
POFILES =  it.po ko.po fr.po de.po es.po no.po
POSUB = po
PROGRAMS_PANEL_CDPLAYER = cdplayer
PROGRAMS_PANEL_MIXER = mixer
PTHREAD_LIB = -lpthread
RANLIB = ranlib
RES_LIBS = 
USE_INCLUDED_LIBINTL = no
USE_NLS = yes
VERSION = 0.13
XF86MISC_LIBS = -lXxf86misc
XPM_LIBS = -lXpm
YACC = bison -y
l = 

gnome_intro_helpdir = $(datadir)/gnome/help/gnome-intro/C

GNOME_INTRO_HTML_FILES = \
	gnome-intro/book01.html gnome-intro/c0102.html gnome-intro/c0202.html \
	gnome-intro/c0205.html gnome-intro/c0208.html gnome-intro/f0102.html \
	gnome-intro/c01.html gnome-intro/c02.html gnome-intro/c0203.html \
	gnome-intro/c0206.html gnome-intro/f01.html gnome-intro/c0101.html \
	gnome-intro/c0201.html gnome-intro/c0204.html gnome-intro/c0207.html \
	gnome-intro/f0101.html

GNOME_INTRO_PICTURES = pix/terminal.gif \
	pix/gedit-2files.gif \
	pix/ghex-2files.gif \
	pix/ghex-basic.gif \
	pix/gmc-basic.gif \
	pix/help-browser-initial.gif \
	pix/help-browser-sample.gif \
	pix/help-icon.gif \
	pix/panel-basic.gif \
	pix/panel-menu-select.gif \
	pix/panel-menu.gif \
	pix/gmix.gif \
	pix/gtcd.gif \
	pix/gtop-procs.gif \
	pix/gtcd-track-list.gif \
	pix/gtcd-cddb.gif \
	pix/gulp.gif \
	pix/calendar.gif \
	pix/ee-menu.gif \
	pix/gtop-mem.gif \
	pix/gtop-kill.gif \
	pix/gtt-basic.gif \
	pix/background-properties.gif \
	pix/gtt-new.gif \
	pix/gtt-2proj.gif \
	pix/gcalc.gif \
	pix/freecell.gif \
	pix/mahjongg.gif \
	pix/same-gnome.gif \
	pix/gnomine.gif

INTRO_EXTRA_DIST = gnome-intro.sgml
GNOME_INTRO_GIFS = pix/panel-basic.gif pix/panel-menu.gif \
	pix/panel-menu-select.gif
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_HEADER = ../config.h
CONFIG_CLEAN_FILES = 
DIST_COMMON =  Makefile.am Makefile.in


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP = --best
all: Makefile

.SUFFIXES:
$(srcdir)/Makefile.in:  Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4)
	cd $(top_srcdir) && $(AUTOMAKE) --gnu core-docs/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status $(BUILT_SOURCES)
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status

tags: TAGS
TAGS:


distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = core-docs

distdir: $(DISTFILES)
	here=`cd $(top_builddir) && pwd`; \
	top_distdir=`cd $(top_distdir) && pwd`; \
	distdir=`cd $(distdir) && pwd`; \
	cd $(top_srcdir) \
	  && $(AUTOMAKE) --include-deps --build-dir=$$here --srcdir-name=$(top_srcdir) --output-dir=$$top_distdir --gnu core-docs/Makefile
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  test -f $(distdir)/$$file \
	  || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	  || cp -p $$d/$$file $(distdir)/$$file; \
	done
info:
dvi:
check: all
	$(MAKE)
installcheck:
install-exec: 
	@$(NORMAL_INSTALL)

install-data: install-data-local
	@$(NORMAL_INSTALL)

install: install-exec install-data all
	@:

uninstall: 

install-strip:
	$(MAKE) INSTALL_PROGRAM='$(INSTALL_PROGRAM) -s' INSTALL_SCRIPT='$(INSTALL_PROGRAM)' install
installdirs:


mostlyclean-generic:
	-test -z "$(MOSTLYCLEANFILES)" || rm -f $(MOSTLYCLEANFILES)

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(DISTCLEANFILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)

maintainer-clean-generic:
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
mostlyclean:  mostlyclean-generic

clean:  clean-generic mostlyclean

distclean:  distclean-generic clean
	-rm -f config.status
	-rm -f libtool

maintainer-clean:  maintainer-clean-generic distclean
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

.PHONY: tags distdir info dvi installcheck install-exec install-data \
install uninstall all installdirs mostlyclean-generic distclean-generic \
clean-generic maintainer-clean-generic clean mostlyclean distclean \
maintainer-clean


install-data-local:
	$(mkinstalldirs) $(gnome_intro_helpdir)
	$(mkinstalldirs) $(gnome_intro_helpdir)/gnome-intro
	$(mkinstalldirs) $(gnome_intro_helpdir)/gnome-intro/pix
	$(INSTALL_DATA) $(srcdir)/topic.dat $(gnome_intro_helpdir)/topic.dat
	$(INSTALL_DATA) $(srcdir)/gnome-intro.html $(gnome_intro_helpdir)/index.html
	$(INSTALL_DATA) $(GNOME_INTRO_HTML_FILES) $(gnome_intro_helpdir)/gnome-intro
	$(INSTALL_DATA) $(GNOME_INTRO_PICTURES) $(gnome_intro_helpdir)/gnome-intro/pix

manual-html: gnome-intro/book01.html
	cp gnome-intro/book01.html gnome-intro.html
manual-ps: gnome-intro.ps
manual-rtf: gnome-intro.rtf
manual-all: manual-html manual-ps manual-rtf

%.dvi: %.sgml
	db2dvi $<

%.ps: %.dvi
	dvips -o $@ $<

%/book01.html: %.sgml
	db2html $<

%.rtf: %.sgml
	db2rtf $<

gnome-intro/book01.html: gnome-intro.sgml
	db2html gnome-intro.sgml
	mkdir gnome-intro/pix
	cp pix/*.gif gnome-intro/pix
#gnome-intro.ps: gnome-intro.dvi
#	dvips gnome-intro.dvi
#gnome-intro.rtf: gnome-intro.sgml
#	db2rtf gnome-intro.sgml

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
