/* If your name uses some letters not in 7bit ascii, or a non-lati script;
 * put your name in ascii enclosed with N_( ) and put a comment before your
 * line giving some info on how it should be written for languages that
 * support the proper letters/script for your name. So for example someone
 * with a name normally written in cyrillic can have it displayed in cyrillic
 * for those languages supporting it */ 


/* Please keep this in alphabetical order */
static const gchar *contributors[] = {
	"Adam Fritzler",
	"Alan Aspuru Guzik",
	"Alan Cox",
	"Alejandro Aguilar Sierra",
	"Alexander Kirillov",
	"Alexander Larsson",
	"Alexandre Mu\xc3\xb1iz",
	"Alex Duggan",
	"Alex Roberts",
	"Alfredo Kojima",
	"Anders Carlsson",
	"Andreas Beck",
	"Andreas Bolsch",
	"Andreas Czechanowski",
	"Andreas Hyden",
	"Andrew Clausen",
	"Andrew Kuchling",
	"Andrew Sobala",
	"Andrew Veliath",
	"Andy Kahn",
	"Anthony Taylor",
	"Arturo Espinosa",
	"Arturo Tena",
	"Arvind Samptur",
	"Asger Alstrup Nielsen",
	"Bastien Nocera",
	"Ben FrantzDale",
	"Ben Pierce",
	"Ben Stern",
	"Bernd Schroeder",
	"Bertrand Guiheneuf",
	"Bibek Sahu",
	"Birger Langkjer",
	"Bj\xc3\xb6rn Giesler",
	"Brian Cameron",
	"Bruno Widmann",
	"Calum Benson",
	"Cameron Parish",
	"Carlos Amador Bedolla",
	"Carlos Garc\xc3\xad" "a Campos",
	"Carlos Garnacho Parro",
	"Carlos Perell\xc3\xb3 Mar\xc3\xadn",
	"Carsten Schaar",
	"Cesar Miquel",
	"Chad Clark",
	"Chema Celorio",
	"Chris Lahey",
	"Chris Pinkham",
	"Christian Bucher",
	"Christian Kirbach",
	"Christian Meyer",
	"Christian Neumair",
	"Christian Rose",
	"Christian Schaller",
	"Christof Petig",
	"Christophe Fergeau",
	"Christophe Merlet",
	"Christopher Blizzard",
	"Christopher R. Gabriel",
	"Christoph Toshok",
	"Chris Toshok",
	"Cody Russell",
	"Conrad Parker",
	"Damon Chaplin",
	"Dan Damian",
	"Daniel Manrique",
	"Daniel Nylander",
	"Daniel Veillard",
	"Dan Mueth",
	"Dario Bressanini",
	"Dave Bordoley",
	"Dave Camp",
	"Dave Finton",
	"Dave Glowacki",
        "Dave Mason",
	"David Abilleira Freijeiro",
	"David Etherton",
	"David F. Skoll",
	"David Huggins-Daines",
	"David Mosberger",
	"David Orme",
	"David Winkler",
	"Davyd Madeley",
	"Deepa Natarajan",
	"Dennis Cranston",
	"Dick Porter",
	"Didier Carlier",
	"Dietmar Maurer",
	"Dirk Lutjens",
	"Djihed Afifi",
	"Dodji Seketeli",
	"Dov Grobgeld",
	"Eckehard Berns",
	"Elijah Newren",
	"Elliot Lee",
	"Emmanuel Briot",
	"Emmanuele Bassi",
	"Eric B. Mitchell",
	"Eric Nielson",
	"Erik Andersen",
	"Erwann Ch\xc3\xa9ned\xc3\xa9",
	"Eskil Olsen",
	"Ettore Perazzoli",
	"Evan Lawrence",
	"Fabio Marzocca",
	"Fatih Demir",
	"Federico Mena-Quintero",
	"Feico W. Dillema",
        "Fernando Herrera",
	"Francis J. Lacoste",
	"Franck Schneider",
	"Frank Belew",
	"Frank Worsley",
	"Fredrik Hallenberg",
	"Fr\xc3\xa9" "d\xc3\xa9ric Crozat",
	"Fr\xc3\xa9" "d\xc3\xa9ric Devernay",
	"Gael Chamoulaud",
	"Garrett LeSage",
	"Garrett Smith",
	"George Lebl",
	"Gerg\xc5\x91 \xc3\x89rdi",
	"Germ\xc3\xa1n Poo-Caama\xc3\xb1o",
	"Glynn Foster",
	"Gordon Matzigkeit",
	"Gregory Leblanc",
	"Gregory McLean",
	"Guilherme de S. Pastore",
	"Guillaume Laurent",
	"Gus Estrella",
	"Hasbullah Bin Pit",
	"Havoc Pennington",
	"Heath Harrelson",
	"Heath Martin",
	"Helmut K\xc3\xb6" "berle",
	"HideToshi Tajima",
	"Iain Holmes",
	"Ian Main",
	"Ian Peters",
	"Ingo Schneider",
	"Istvan Szekeres",
	"I\xc3\xb1igo Serna",
	"Jacob Berkman",
	"Jaka Mocnik",
	"Jakub Steiner",
	"James Henstridge",
	"James Mastros",
	"James Willcox",
	"James Youngman",
	"Jamin Philip Gray",
	"Jason Leach",
	"Jason van Zyl",
	"Jay Painter",
	"Jeff Freedman",
	"Jeff Garzik",
	"Jeffrey Stedfast",
	"Jeff Waugh",
	"Jens Christian Restemeier",
	"Jens Finke",
	"Jens Lautenbacher",
	"Jeremy Collins",
	"Jeremy Wise",
	"Jimmy Olsen",
	"Joaquim Fellmann",
	"Jochen Friedrich",
	"Joe Pfeiffer",
	"Joe Shaw",
	"Johan Dahlin",
	"John Ellis",
	"John Fleck",
	"John Schulien",
	"John Slee",
	"Jon Anhold",
	"Jonathan Blandford",
	"Jon Trowbridge",
        "Jordi Mallach",
	"Josh MacDonald",
	"Josh Sled",
	"Julian Missig",
	"Justin Maurer",
	"J\xc3\xa9r\xc3\xb4me Abela",
	"J\xc3\xa9r\xc3\xb4me Bolliet",
	"Karl Anders Oygard",
	"Karl Eichwalder",
	"Karl Nelson",
	"Karsten Br\xC3\xA4" "ckelmann",
	"Kaushal Kumar",
	"Kenneth Rohde Christiansen",
	"Kenny Graunke",
	"Kevin Charter",
	"Kimball Thurston",
	"Kjartan Maraas",
	"Kristian Rietveld",
	"Larry Ewing",
	"Lars Hamann",
	"Lars Rydlinge",
	"Lauri Alanko",
	"Lawrence Foard",
	"Lucas Rocha",
	"Luis Villa",
	"Maciej Stachowiak",
	"Malcolm Tredinnick",
	"Mandrake",
	"Manish Singh",
	"Manish Vachharajani",
	"Marc Ewing",
	"Marc Lehmann",
	"Marcus Brubaker",
	"Marius Andreiana",
	"Marius Vollmer",
	"Mark Crichton",
	"Mark Finlay",
	"Mark Galassi",
	"Mark McLoughlin",
	"Martijn van Beers",
        "Martin Baulig",
	"Martin Kasper Petersen",
	"Martin Kretzschmar",
	"Martin Norb\xc3\xa4" "ck",
	"Martynas Kunigelis",
	"Mathieu Lacage", 
	"Matthew Garrett",
	"Matthew Marjanovic",
	"Matthias Clasen",
	"Matthias Warkus",
	"Matt Loper",
	"Micah Stetson",
	"Michael Fulbright",
	"Michael Hanni",
	"Michael Kellen",
	"Michael K. Johnson",
	"Michael Lausch",
	"Michael Meeks",
	"Michael Zucchi",
	"Michel Roelofs",
	"Miguel de Icaza",
        "Mikael Hallendal",
	"Mike Newman",
	"Milon Firikis",
	"Miroslav Silovic",
	"Nat Friedman",
	"Nathan Carl Summers",
	"Neil Vachharajani",
	"Nick Lopez",
	"Nils Pedersen",
	"Nuke Skyjumper",
	"Olav Vitters",
	"Ole Laursen",
	"Oliver Maruhn",
	"Oliver Rauch",
	"Olof Kylander",
	"Orest Zborowski",
	"Owen Taylor",
	"Pablo Saratxaga",
	"Paolo Bacchilega",
	"Paolo Maggi",
	"Paolo Molaro",
	"Pat Costello",
	"Patrick Reynolds",
	"Peter Fales",
	"Peter Hawkins",
	"Peter Kirchgessner",
	"Peter Mattis",
	"Peter Ryland",
	"Peter Teichman",
	"Phil Dawes",
	"Radek Doulik",
	"Raja R Harinath",
	"Randy Gordon",
	"Raph Levien",
	"Ra\xc3\xbal Perusquia Flores",
	"Reklaw",
	"Richard Hestilow",
	"Richard Hult",
	"Rob Adams",
	"Robert Bihlmeyer",
	"Robert Richardson",
	"Robert Wilhelm",
	"Rodrigo Moya",
	"Roger Wolff",
	"Ross Burton",
	"Rusty Conover",
	"Ryan Lortie",
	"Sami Kananoja",
	"Sam Magnuson",
	"Sascha Ziemann",
	"Scott Goehring",
	"Scott Heavner",
	"Scott Laird",
	"Sebastian Wilhelmi",
	"Seth Alves",
	"Seth Nickell",
	"Shaleh",
	"Shaun McCance",
	"Shawn T. Amundson",
	"Shawn Wagner",
	"Spencer Kimball",
	"Stalyn",
	"Stefan Jeske",
	"Stephan Kulow",
	"Stephen Browne",
	"Stephen Kiernan",
	"Stuart Parmenter",
	"Suzanna Smith",
	"S\xc3\xb8ren Sandmann",
	"Szabolcs 'Shooby' B\xc3\xa1n",
	"Ted Gould",
	"Telsa Gwynne",
	"Tero Pulkkinen",
	"The Rasterman",
	"Thomas Muldowney",
	"Thomas Thurman",
	"Thomas Vander Stichele",
	"Tim Gerla",
	"Tim Janik",
	"Timo Sirainen",
	"Timur I. Bakeyev",
	"Tomas \xc3\x96gren",
	"Tom Bech",
	"Tom Dyas",
	"Tom Tromey",
	"Tony Gale",
	"Tristan Tarrant",
	"Tuomas Kuosmanen",
	"Ueli Rutishauser",
	"Vendu",
	"Vincent Untz",
	"Wayne Schuller",
	"Will LaShell",
	/* Danilo Segan */
	"'\xd0\x94\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xbb\xd0\xbe\x20\xd0\xa8\xd0\xb5\xd0\xb3\xd0\xb0\xd0\xbd",
	/* Sergey V. Udaltsov */
	"\xd0\xa1\xd0\xb5\xd1\x80\xd0\xb3\xd0\xb5\xd0\xb9 \xd0\x92. \xd0\xa3\xd0\xb4\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x86\xd0\xbe\xd0\xb2",
	/* Abel Cheung: */
	"\xe5\xbc\xb5 \xe5\x9c\x8b \xe5\x86\xa0",
	/* Wang Jian: */
	"\xe7\x8e\x8b \xe5\x89\x91",
	/* Kazuhiro Sasayama: */
	"\xe7\xac\xb9 \xe5\xb1\xb1 \xe5\x92\x8c \xe5\xae\x8f",
	/* Sung-Hyun Nam: */
	"\xeb\x82\xa8 \xec\x84\xb1 \xed\x98\x84",
	N_("The Mysterious GEGL"),
	N_("The Squeaky Rubber Gnome"),
	N_("Wanda The GNOME Fish")
};

