/* If your name uses some letters not in 7bit ascii, or a non-latin script;
 * put your name in ascii enclosed with N_( ) and put a comment before your
 * line giving some info on how it should be written for languages that
 * support the proper letters/script for your name. So for example someone
 * with a name normally written in cyrillic can have it displayed in cyrillic
 * for those languages supporting it */ 


/* Please keep this in alphabetical order */
static const gchar *contributors[] = {
	"J\xc3\xa9r\xc3\xb4me Abela",
	"Rob Adams",
	"Djihed Afifi",
	"Sarfraaz Ahmed",
	"Christopher Aillon",
	"Lauri Alanko",
	"\xd0\x91\xd0\xbe\xd1\x80\xd0\xb8\xd1\x81\xd0\xbb\xd0\xb0\xd0\xb2 \xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x80\xd0\xbe\xd0\xb2 (Borislav Aleksandrov)",
	"Seth Alves",
	"Shawn T. Amundson",
	"Robert Ancell",
	"Erik Andersen",
	"\xd0\xa4\xd0\xb8\xd0\xbb\xd0\xb8\xd0\xbf \xd0\x90\xd0\xbd\xd0\xb4\xd0\xbe\xd0\xbd\xd0\xbe\xd0\xb2 (Filip Andonov)",
	"Marius Andreiana",
	"Jon Anhold",
	"\xd0\x90\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb3\xd0\xb5\xd0\xbb \xd0\x90\xd0\xbd\xd0\xb3\xd0\xbe\xd0\xb2 (Arangel Angov)",
	"\xd0\x9d\xd0\xb8\xd0\xba\xd0\xbe\xd0\xbb\xd0\xb0 \xd0\x90\xd0\xbd\xd1\x82\xd0\xbe\xd0\xbd\xd0\xbe\xd0\xb2 (Nikola Antonov)",
	"Sandy Armstrong",
	"Frank Arnold",
	"Arunprakash",
	"Paolo Bacchilega",
	"Peter Bach",
	"Timur I. Bakeyev",
	"S\xc3\xa9bastien Bacher",
	"Chris Ball",
	"Szabolcs 'Shooby' B\xc3\xa1n",
	"Lasse Bang Mikkelsen",
	"Matthew Barnes",
	"Seba Barto",
	"Emmanuele Bassi",
        "Martin Baulig",
	"Tom Bech",
	"Andreas Beck",
	"Carlos Amador Bedolla",
	"Martijn van Beers",
	"Frank Belew",
	"Calum Benson",
	"Jacob Berkman",
	"Eckehard Berns",
	"Runa Bhattacharjee",
	"Robert Bihlmeyer",
	"Jonathan Blandford",
	"Christopher Blizzard",
	"\xd0\x95\xd0\xb2\xd0\xb3\xd0\xb5\xd0\xbd\xd0\xb8 \xd0\x91\xd0\xbe\xd0\xb5\xd0\xb2\xd1\x81\xd0\xba\xd0\xb8 (Evgeni Boevski)",
	"J\xc3\xa9r\xc3\xb4me Bolliet",
	"Andreas Bolsch",
	"Wouter Bolsterlee",
	"David Bolter",
	"Dave Bordoley",
	"Paolo Borelli",
	"James Bowes",
	"Karsten Br\xC3\xA4" "ckelmann",
	"Hendrik Brandt",
	"Dario Bressanini",
	"Emmanuel Briot",
	"Stephen Browne",
	"Marcus Brubaker",
	"Christian Bucher",
	"Ronald S. Bultje",
	"Rich Burridge",
	"Ross Burton",
	"Jeff Cai",
	"Brian Cameron",
	"Dave Camp",
	"Didier Carlier",
	"Anders Carlsson",
	"Luca Cavalli",
	"Chema Celorio",
	"Youssef Chahibi",
	"Ga\xc3\xabl Chamoulaud",
	"\xd0\xa1\xd0\xb0\xd0\xb2\xd0\xb0 \xd0\xa7\xd0\xb0\xd0\xbd\xd0\xba\xd0\xbe\xd0\xb2 (Sava Chankov)",
	"Damon Chaplin",
	"Kevin Charter",
	"Erwann Ch\xc3\xa9ned\xc3\xa9",
	 /* Abel Cheung: */
	"\xe5\xbc\xb5 \xe5\x9c\x8b \xe5\x86\xa0",
	"\xd0\x9f\xd0\xb0\xd0\xb2\xd0\xb5\xd0\xbb \xd0\xa7\xd0\xbe\xd0\xbb\xd0\xb0\xd0\xba\xd0\xbe\xd0\xb2 (Pavel Cholakov)",
	"Kenneth Rohde Christiansen",
	"Bryan Clark",
	"Chad Clark",
	"Matthias Clasen",
	"Andrew Clausen",
	"Jason Clinton",
	"Jules Colding",
	"Jeremy Collins",
	"Rusty Conover",
	"Pat Costello",
	"Phil Cowans",
	"Alan Cox",
	"Dennis Cranston",
	"Mark Crichton",
	"Fr\xc3\xa9" "d\xc3\xa9ric Crozat",
	"Andreas Czechanowski",
	"\xd0\x92\xd0\xb8\xd0\xba\xd1\x82\xd0\xbe\xd1\x80 \xd0\x94\xd0\xb0\xd1\x87\xd0\xb5\xd0\xb2 (Victor Dachev)",
	"Johan Dahlin",
	"Nalin Dahyabhai",
	"Dan Damian",
	"Sayamindu Dasgupta",
	"Phil Dawes",
	"Fatih Demir",
	"Guillaume Desmottes",
	"Fr\xc3\xa9" "d\xc3\xa9ric Devernay",
	"Joanmarie Diggs",
	"Feico W. Dillema",
	"\xd0\xa4\xd0\xb8\xd0\xbb\xd0\xb8\xd0\xbf \xd0\x94\xd0\xb8\xd0\xbc\xd0\xb8\xd1\x82\xd1\x80\xd0\xbe\xd0\xb2 (Philip Dimitrov)",
	"Carlos Eduardo Rodrigues Di\xc3\xb3genes",
	"\xd0\xa1\xd1\x82\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xbc\xd0\xb8\xd1\x80 \xd0\x94\xd0\xb6\xd0\xb5\xd0\xb2\xd0\xb5\xd0\xbb\xd0\xb5\xd0\xba\xd0\xbe\xd0\xb2 (Stanimir Djevelekov)",
	"\xd0\x9f\xd0\xb5\xd1\x82\xd1\x8a\xd1\x80 \xd0\x94\xd0\xbe\xd0\xb1\xd1\x80\xd0\xb5\xd0\xb2 (Peter Dobrev)",
	"\xd0\xaf\xd0\xb2\xd0\xbe\xd1\x80 \xd0\x94\xd0\xbe\xd0\xb3\xd0\xb0\xd0\xbd\xd0\xbe\xd0\xb2 (Yavor Doganov)",
	"Radek Doulik",
	"Sebastian Dr\xc3\xb6ge",
	"M\xc3\xa1ir\xc3\xadn Duffy",
	"Alex Duggan",
	"L\xc3\xa1szl\xc3\xb3 Dvornik",
	"Tom Dyas",
	"Karl Eichwalder",
	"John Ellis",
	"Diego Escalante Urrelo",
	"Behdad Esfahbod",
	"Arturo Espinosa",
	"Gus Estrella",
	"David Etherton",
	"Larry Ewing",
	"Marc Ewing",
	"Gerg\xc5\x91 \xc3\x89rdi",
	"Peter Fales",
	"Ahmad Farghal",
	"Joaquim Fellmann",
	"Christophe Fergeau",
	"Jens Finke",
	"Mark Finlay",
	"Dave Finton",
	"Milon Firikis",
	"John Fleck",
	"Ra\xc3\xbal Perusquia Flores",
	"Crispin Flowerday",
	"Lawrence Foard",
	"Leonardo Fontenelle",
	"Glynn Foster",
	"Ben FrantzDale",
	"Jeff Freedman",
	"David Abilleira Freijeiro",
	"Nat Friedman",
	"Jochen Friedrich",
	"Adam Fritzler",
	"Michael Fulbright",
	"Christopher R. Gabriel",
	"Mark Galassi",
	"Tony Gale",
	"Carlos Garc\xc3\xad" "a Campos",
	"Matthew Garrett",
	"Carlos Garnacho Parro",
	"Jeff Garzik",
	"Vincent Geddes",
	N_("The Mysterious GEGL"),
	"\xd0\x92\xd0\xbb\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xbc\xd0\xb8\xd1\x80 \xd0\x93\xd0\xb5\xd1\x80\xd0\xb4\xd0\xb6\xd0\xb8\xd0\xba\xd0\xbe\xd0\xb2 (Vladimir Gerdjikov)",
	"Tim Gerla",
	"Bj\xc3\xb6rn Giesler",
	"Quim Gil",
	"\xd0\x92\xd0\xbb\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xbc\xd0\xb8\xd1\x80\xd0\xb0 \xd0\x93\xd0\xb8\xd1\x80\xd0\xb3\xd0\xb8\xd0\xbd\xd0\xbe\xd0\xb2\xd0\xb0 (Vladimira Girginova)",
	"Dave Glowacki",
	"Scott Goehring",
	"Jody Goldberg",
	"Randy Gordon",
	"Ted Gould",
	"Jens Granseuer",
	"Kenny Graunke",
	"Alex Graveley",
	"Jamin Philip Gray",
	"Dov Grobgeld",
	"Bertrand Guiheneuf",
	"Alan Aspuru Guzik",
	"Telsa Gwynne",
	"Fredrik Hallenberg",
        "Mikael Hallendal",
	"Lars Hamann",
	"Bill Haneman",
	"Michael Hanni",
	"Raja R Harinath",
	"Heath Harrelson",
	"Peter Harvey",
	"Mathias Hasselmann",
	"Peter Hawkins",
	"Chris Heath",
	"Scott Heavner",
	"Sebastian Heinlein",
	"Jon K Hellan",
	"James Henstridge",
        "Fernando Herrera",
	"Richard Hestilow",
	"Thomas Hinkle",
	"Iain Holmes",
	"Adam Hooper",
	"Alan Horkan",
	"Khaled Hosny",
	"Ihar Hrachyshka",
	"\xd0\x9d\xd0\xb8\xd0\xba\xd0\xbe\xd0\xbb\xd0\xb0\xd0\xb9 \xd0\xa5\xd1\x80\xd0\xb8\xd1\x81\xd1\x82\xd0\xbe\xd0\xb2 (Nikolay Hristov)",
	"Irene Huang",
	"Richard Hughes",
	"David Huggins-Daines",
	"Richard Hult",
	"Andreas Hyden",
	"Miguel de Icaza",
	"Hiroyuki Ikezoe",
	"Khandakar Mujahidul Islam",
	"Johnny Jacob",
	"Mayank Jain",
	"Vivek Jain",
	"Tim Janik",
	"Stefan Jeske",
	/* Wang Jian: */
	"\xe7\x8e\x8b \xe5\x89\x91",
	"Amed \xc3\x87. Jiyan",
	"Michael K. Johnson",
	"Keld J\xc3\xb8rn Simonsen",
	"Andy Kahn",
	"Mikkel Kamstrup Erlandsen",
	"Sami Kananoja",
	"\xd0\xaf\xd0\xbd\xd0\xba\xd0\xbe \xd0\x9a\xd0\xb0\xd0\xbd\xd0\xb5\xd1\x82\xd0\xb8 (Yanko Kaneti)",
	"\xd0\x98\xd0\xb2\xd0\xb5\xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb0 \xd0\x9a\xd1\x8a\xd1\x80\xd1\x87\xd0\xb5\xd0\xb2\xd0\xb0 (Ivelina Karcheva)",
	"Theppitak Karoonboonyanan",
	"Matt Keenan",
	"g\xc3\xa1bor Kelemen",
	"Michael Kellen",
	"Stephen Kiernan",
	"Spencer Kimball",
	"Christian Kintner",
	"Christian Kirbach",
	"Peter Kirchgessner",
	"Alexander Kirillov",
	"\xd0\x94\xd0\xb8\xd0\xbc\xd0\xb8\xd1\x82\xd1\x8a\xd1\x80 \xd0\x9a\xd0\xb8\xd1\x80\xd0\xbe\xd0\xb2 (Dimitar Kirov)",
	"Andre Klapper",
	"Helmut K\xc3\xb6" "berle",
	"Alfredo Kojima",
	"\xd0\x90\xd1\x82\xd0\xb0\xd0\xbd\xd0\xb0\xd1\x81 \xd0\x9a\xd0\xbe\xd1\x88\xd0\xb0\xd1\x80\xd0\xbe\xd0\xb2 (Atanas Kosharov)",
	"Martin Kretzschmar",
	"Harish Krishnaswamy",
	"Andrew Kuchling",
	"Stephan Kulow",
	"Kaushal Kumar",
	"Nirmal Kumar",
	"Praveen Kumar",
	"Martynas Kunigelis",
	"Tuomas Kuosmanen",
	"Olof Kylander",
	"Mathieu Lacage", 
	"Francis J. Lacoste",
	"Chris Lahey",
	"Dom Lachowicz",
	"Scott Laird",
	"Birger Langkjer",
	"Ask Hjorth Larsen",
	"Alexander Larsson",
	"Guillaume Laurent",
	"Ole Laursen",
	"Michael Lausch",
	"Will LaShell",
	"Jens Lautenbacher",
	"Evan Lawrence",
	"Garrett LeSage",
	"Jason Leach",
	"George Lebl",
	"Gregory Leblanc",
	"Elliot Lee",
	"Marc Lehmann",
	"Noah Levitt",
	"Raph Levien",
	/* Chao-Hsiung Liao: */
	"\xe5\xbb\x96 \xe6\x98\xad \xe9\x9b\x84",
	"Tor Lillqvist",
	"Matt Loper",
	"Nick Lopez",
	"Xan Lopez",
	"Elixan Loran",
	"Ryan Lortie",
	"Harry Lu",
	"Dirk Lutjens",
	"Josh MacDonald",
	"Og Maciel",
	"David MacKay",
	"Davyd Madeley",
	"Mohamed Magdy",
	"Paolo Maggi",
	"Sam Magnuson",
	"Ian Main",
	"David Malcolm",
        "Jordi Mallach",
	"Mandrake",
	"Daniel Manrique",
	"Kjartan Maraas",
	"Matthew Marjanovic",
	"Heath Martin",
	"Oliver Maruhn",
	"Fabio Marzocca",
        "Dave Mason",
	"James Mastros",
	"Peter Mattis",
	"Gordon Matzigkeit",
	"Dietmar Maurer",
	"Justin Maurer",
	"Shaun McCance",
	"William Jon McCann",
	"Callum McKenzie",
	"Gregory McLean",
	"Mark McLoughlin",
	"Michael Meeks",
	"Federico Mena-Quintero",
	"Christophe Merlet",
	"Christian Meyer",
	"Tim Miao",
	"Cesar Miquel",
	"Julian Missig",
	"Eric B. Mitchell",
	"Jaka Mocnik",
	"Paolo Molaro",
	"Lynn Monsanto",
	"David Mosberger",
	"Rodrigo Moya",
	"Dan Mueth",
	"Thomas Muldowney",
	"Alexandre Mu\xc3\xb1iz",
	"Tim-Philipp M\xc3\xbcller",
	"Sivaiah Nallagatla",
	/* Sung-Hyun Nam: */
	"\xeb\x82\xa8 \xec\x84\xb1 \xed\x98\x84",
	"Deepa Natarajan",
	"Ales Navicki",
	"\xd0\x88\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd \xd0\x9d\xd0\xb0\xd1\x83\xd0\xbc\xd0\xbe\xd0\xb2\xd1\x81\xd0\xba\xd0\xb8 (Jovan Naumovski)",
	"Dave Neary",
	"Karl Nelson",
	"Elijah Newren",
	"Christian Neumair",
	"Mike Newman",
	"Seth Nickell",
	"Asger Alstrup Nielsen",
	"Kenneth Nielsen",
	"Nate Nielsen",
	"Eric Nielson",
	"Bastien Nocera",
	"Martin Norb\xc3\xa4" "ck",
	"Joachim Noreiko",
	"Alexander Nyakhaychyk",
	"Daniel Nylander",
	"Padraig O'Briain",
	"Eskil Olsen",
	"Jimmy Olsen",
	"David Orme",
	"Karl Anders Oygard",
	"Tomas \xc3\x96gren",
	"Keith Packard",
	"Jay Painter",
	"Chenthill Palanisamy",
	"John Palmieri",
	"Cameron Parish",
	"Conrad Parker",
	"Stuart Parmenter",
	"Guilherme de S. Pastore",
	"Sankarasivasubramaniam Pasupathilingam",
	/* Danilo Segan */
	"\xd0\x94\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xbb\xd0\xbe\x20\xd0\xa8\xd0\xb5\xd0\xb3\xd0\xb0\xd0\xbd",
	"Mike Pedersen",
	"Nils Pedersen",
	"\xd0\x98\xd0\xbb\xd0\xb8\xd1\x8f \xd0\x9f\xd0\xb5\xd0\xbd\xd0\xb5\xd0\xb2 (Ilia Penev)",
	"Havoc Pennington",
	"Ettore Perazzoli",
	"Carlos Perell\xc3\xb3 Mar\xc3\xadn",
	"Christian Persch",
	"Marco Pesenti Gritti",
	"Ian Peters",
	"Martin Kasper Petersen",
	"Christof Petig",
	"\xd0\x92\xd0\xbb\xd0\xb0\xd0\xb4\xd0\xb8\xd0\xbc\xd0\xb8\xd1\x80 \xd0\x9f\xd0\xb5\xd1\x82\xd0\xba\xd0\xbe\xd0\xb2 (Vladimir \"Kaladan\" Petkov)",
	"Joe Pfeiffer",
	"Ben Pierce",
	"Chris Pinkham",
	"Hasbullah Bin Pit",
	"Sebastian P\xc3\xb6lsterl",
	"Germ\xc3\xa1n Poo-Caama\xc3\xb1o",
	"\xd0\x9f\xd0\xb5\xd0\xb9\xd0\xbe \xd0\x9f\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xb2 (Peio Popov)",
	"Dick Porter",
	"\xd0\xaf\xd1\x81\xd0\xb5\xd0\xbd \xd0\x9f\xd1\x80\xd0\xb0\xd0\xbc\xd0\xb0\xd1\x82\xd0\xb0\xd1\x80\xd0\xbe\xd0\xb2 (Yasen Pramatarov)",
	"Tero Pulkkinen",
	"\xd0\x90\xd1\x82\xd0\xb0\xd0\xbd\xd0\xb0\xd1\x81 \xd0\x9f\xd1\x8e\xd1\x81\xd0\xba\xd1\x8e\xd0\xbb\xd0\xb5\xd0\xb2 (Atanas Pyuskyulev)",
	"Sushma Rai",
	"\xd0\xa0\xd0\xbe\xd1\x81\xd1\x82\xd0\xb8\xd1\x81\xd0\xbb\xd0\xb0\xd0\xb2 \xd0\xa0\xd0\xb0\xd0\xb9\xd0\xba\xd0\xbe\xd0\xb2 (Rostislav \"zbrox\" Raikov)",
	"Madhan Raj M.",
	"Srinivasa Ragavan",
	"Rajeev Ramanathan",
	"Jean-Fran\xc3\xa7ois Rameau",
	"Sriram Ramkrishna",
	"The Rasterman",
	"Oliver Rauch",
	"Lucas Rocha",
	"Erdal Ronahi",
	"Andreas R\xc3\xb8sdal",
	"Christian Rose",
	"Cody Russell",
	"Reklaw",
	"Jens Christian Restemeier",
	"Patrick Reynolds",
	"Robert Richardson",
	"Hendrik Richter",
	"Kristian Rietveld",
	"Sebastian Rittau",
	"Alex Roberts",
	"Michel Roelofs",
	"Ueli Rutishauser",
	"Lars Rydlinge",
	"Peter Ryland",
	"Claudio Saavedra",
	"Joseph Sacco",
	"Bibek Sahu",
	"Arvind Samptur",
	"S\xc3\xb8ren Sandmann",
	"Damien Sandras",
	"Pablo Saratxaga",
	/* Kazuhiro Sasayama: */
	"\xe7\xac\xb9 \xe5\xb1\xb1 \xe5\x92\x8c \xe5\xae\x8f",
	"Carsten Schaar",
	"Christian Schaller",
	"Wayne Schuller",
	"Franck Schneider",
	"Ingo Schneider",
	"Bernd Schroeder",
	"John Schulien",
	"Chris Scobell",
	"Don Scorgie",
	"Jens Seidel",
	"Dodji Seketeli",
	"Shakti Sen",
	"I\xc3\xb1igo Serna",
	"Shaleh",
	"Devashish Sharma",
	"Joe Shaw",
	"\xd0\x90\xd0\xbb\xd0\xb5\xd0\xba\xd1\x81\xd0\xb0\xd0\xbd\xd0\xb4\xd1\x8a\xd1\x80 \xd0\xa8\xd0\xbe\xd0\xbf\xd0\xbe\xd0\xb2 (Alexander Shopov)",
	"Clytie Siddall",
	"Alejandro Aguilar Sierra",
	"Miroslav Silovic",
	"Manish Singh",
	"Timo Sirainen",
	"David F. Skoll",
	"Jochen Skulj",
	"Nuke Skyjumper",
	"\xd0\x9f\xd0\xb5\xd1\x82\xd1\x8a\xd1\x80 \xd0\xa1\xd0\xbb\xd0\xb0\xd0\xb2\xd0\xbe\xd0\xb2 (Peter \"Peshka\" Slavov)",
	"Josh Sled",
	"John Slee",
	"Rapha\xc3\xabl Slinckx",
	"Brent Smith",
	"Garrett Smith",
	"Suzanna Smith",
	"Andrew Sobala",
	N_("The Squeaky Rubber Gnome"),
	"Shreyas Srinivasan",
	"Maciej Stachowiak",
	"Stalyn",
	"Jeffrey Stedfast",
	"Jakub Steiner",
	"Ben Stern",
	"Micah Stetson",
	"Ray Strode",
	"Mariano Su\xc3\xa1rez-Alvarez",
	"Parthasarathi Susarla",
	"Nathan Carl Summers",
	"Istvan Szekeres",
	"\xd0\x9f\xd0\xb5\xd1\x82\xd1\x8a\xd1\x80 \xd0\xa2\xd0\xb0\xd1\x85\xd1\x87\xd0\xb8\xd0\xb5\xd0\xb2 (Peter Tahchiev)",
	"HideToshi Tajima",
	"Nigel Tao",
	"Tristan Tarrant",
	"Anthony Taylor",
	"Owen Taylor",
	"Peter Teichman",
	"Arturo Tena",
	"Thomas Thurman",
	"Kimball Thurston",
	"Andr\xc3\xa1s T\xc3\xadm\xc3\xa1r",
	"Boyd Timothy",
	"R\xc3\xaazan Tovj\xc3\xaen",
	"Alp Toker",
	"Chris Toshok",
	"Christoph Toshok",
	"Malcolm Tredinnick",
	"Tom Tromey",
	"David Trowbridge",
	"Jon Trowbridge",
	/* Woodman Tuen: */
	"\xe6\xae\xb5 \xe6\xb4\xbb \xe6\x96\x87",
	/* Sergey V. Udaltsov */
	"\xd0\xa1\xd0\xb5\xd1\x80\xd0\xb3\xd0\xb5\xd0\xb9 \xd0\x92. \xd0\xa3\xd0\xb4\xd0\xb0\xd0\xbb\xd1\x8c\xd1\x86\xd0\xbe\xd0\xb2",
	"Juan Pablo Ugarte",
	"Vincent Untz",
	"Manish Vachharajani",
	"Neil Vachharajani",
	"Tristan Van Berkom",
	"Philip Van Hoof",
	"Thomas Vander Stichele",
	"Veerapuram Varadhan",
	"\xd0\x92\xd0\xb0\xd1\x81\xd0\xb8\xd0\xbb \xd0\x92\xd0\xb0\xd1\x81\xd0\xb8\xd0\xbb\xd0\xb5\xd0\xb2 (Vasil Vasilev)",
	"Daniel Veillard",
	"Vendu",
	"Andrew Veliath",
	"\xd0\xae\xd0\xbb\xd0\xb8\xd1\x8f \xd0\x92\xd0\xb5\xd0\xbb\xd0\xba\xd0\xbe\xd0\xb2\xd0\xb0 (Julia Velkova)",
	"Luis Villa",
	"Olav Vitters",
	"Marius Vollmer",
	"Patrick Wade",
	"Shawn Wagner",
	"Will Walker",
	"Hanna Wallach",
	"Colin Walters",
	N_("Wanda The GNOME Fish"),
	"Matthias Warkus",
	"Jeff Waugh",
	"Morten Welinder",
	"Jonh Wendell",
	"Bruno Widmann",
	"Robert Wilhelm",
	"Sebastian Wilhelmi",
	"Dan Williams",
	"James Willcox",
	"David Winkler",
	"Dan Winship",
	"Jeremy Wise",
	"Roger Wolff",
	"Ivan Wong",
	"Frank Worsley",
	"Rizoy\xc3\xaa Xerz\xc3\xae",
	"Wang Xin",
	"James Youngman",
	"Mengjie Yu",
	"Li Yuan",
	"Orest Zborowski",
	"Simon Zheng",
	"Sascha Ziemann",
	"Michael Zucchi",
	"Jason van Zyl"
};

